### PR TITLE
Update buildh script to use Python3

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Review by pc-m — COMMENTED** [review]
I have the following error when I try to execute the script
```
./buildh make
Traceback (most recent call last):
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 113, in <module>
    main()
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 19, in main
    config = read_config(config_filename)
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 46, in read_config
    config = ConfigParser.RawConfigParser()
AttributeError: type object 'ConfigParser' has no attribute 'RawConfigParser'
```

**Comment by sopelj** [comment]
> I have the following error when I try to execute the script
> 
> ```
> ./buildh make
> Traceback (most recent call last):
>   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 113, in <module>
>     main()
>   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 19, in main
>     config = read_config(config_filename)
>   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 46, in read_config
>     config = ConfigParser.RawConfigParser()
> AttributeError: type object 'ConfigParser' has no attribute 'RawConfigParser'
> ```

Oh very sorry. Fixed. 😓

**Comment by pc-m** [comment]
> > I have the following error when I try to execute the script
> > ```
> > ./buildh make
> > Traceback (most recent call last):
> >   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 113, in <module>
> >     main()
> >   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 19, in main
> >     config = read_config(config_filename)
> >   File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 46, in read_config
> >     config = ConfigParser.RawConfigParser()
> > AttributeError: type object 'ConfigParser' has no attribute 'RawConfigParser'
> > ```
> 
> Oh very sorry. Fixed. sweat

I have a new error now

```
Traceback (most recent call last):
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 113, in <module>
    main()
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 35, in main
    command_fun(profile)
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 54, in command_make
    _exec_local_script(local_script)
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 98, in _exec_local_script
    _exec_command([SHELL, '-e'], script)
  File "/home/pcm/dev/wazo/xivo-res-freeze-check/./buildh", line 107, in _exec_command
    p.communicate(process_input)
  File "/usr/lib/python3.10/subprocess.py", line 1137, in communicate
    self._stdin_write(input)
  File "/usr/lib/python3.10/subprocess.py", line 1086, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'
```

**Review by pc-m — APPROVED** [review]

**Comment by sopelj** [comment]
regate

**Comment by sopelj** [comment]
regate

**Pull request merged**
